name: dribbble_financial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  fl_chart: ^0.65.0
  flutter:
    sdk: flutter
  gap: ^3.0.1
  responsive_sizer: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Euclid A
      fonts:
        - asset: assets/fonts/euclid_a_regular.ttf
        - asset: assets/fonts/euclid_a_bold.ttf
          weight: 700
